### ISSUE TITLE
Disallow Elements and Attributes with the Same Uncased Name

### ISSUE THREAD

**Issue by TomCarlson-NTAC** [NIEM/NIEM-NDR#106]
New NDR rule.  Casing will be different due to current rules, but do not allow elements and attributes in the same namespace to have the same name.  This causes problems in case-insensitive environments.

Dr. Scott: Same _uncased_ name. Is there a rule between elements in the same namespace?

#todo Christina and Tom Carlson draft a rule for this.

**Comment by cdmgtri** [comment]
Migrated to niemopen/niem-naming-design-rules#11
