### ISSUE TITLE
Definition Standard Opening Phrases

### ISSUE THREAD

**Issue by TomCarlson-NTAC** [NIEM/NIEM-NDR#108]
Consider if it's worth forcing everyone to start all definitions with a "A(n) ...".

Even the NDR doesn't do this for the few standard opening phrases it defines:

- booleans: True if...; false (otherwise/if...)
- augmentations: Additional information about ...
- metadata: Metadata about ...

People sometimes do weird things to automatically get around it without having to manually rewrite existing definitions, with results being worse than starting with "The ...' or 'Information about ...'.

Mike Hulme: Okay with getting rid of it.
Tom Carlson: Is there a level lower than "should"?
Dr. Scott: Maybe keeping it makes for better definitions.
Dave Hardy: "Warning," "caution," "should" from the Air Force
Tom Carlson: Replace with something better?
Dr. Scott: 11179 Part 4 has some guidance

**Comment by cdmgtri** [comment]
The NTAC has decided to leave the definition standard opening phrases as is.
