### ISSUE TITLE
Representations vs Abstracts (vs Roles)

### ISSUE THREAD

**Issue by TomCarlson-NTAC** [NIEM/NIEM-NDR#113]
Mike Hulme: Can we just use one term?
Christina: Sees a difference between the two.
Mike Hulme: Likes there to be one way to do things, consistent.
Christina: This is different than augmentations. You could still do that. This is specialization.
Chuck Chipman: Need to constrain, can't have one role pointing to multiple people.
Dr. Scott: Show when to use each.

#todo Christina and Tom Carlson

Hard for most of us to figure out when to use `Representation` vs `Abstract`.  Current choices can seem a little arbitrary.

`nc:LanguageType` and `nc:CountryType` both use the `Representation` term for their main code / text substitution groups, but a country or a language isn't inherently a variation of a code set with some additional information thrown in.

A victim could be thought inherently as either a person, organization, or item, with additional victim-specific information to go along with it, but these are represented by `RoleOf` elements.

The need to be able to link different roles to the same base object or a specialized object makes sense (link victim, witness, and officer to the same person object), but:

- the syntax confuses a lot of people at first
- most people don't need it, so it would be nice if they didn't have to use RoleOf elements regardless
- lots of things that could be defined as roles are defined as extensions, because
  - that's the easier thing to do
  - doesn't required advanced NIEM training
  - we can't check it automatically via conformance testing

The important part is probably being able to link various roles to the same base object if needed; not the current syntax we have now.  We might be able to redesign it so it's easier for the 90% use case.  Make it more invisible unless people need to use it.

Note: Using `structures:ref` to point things like a `j:Victim` element and a `j:Witness` element both to the same `nc:Person` element was already rejected as breaking the conceptual model.

A quick idea that will need more thought...

- Get rid of RoleOf elements.
- Use extension, like most people want to do anyway.
- Add either one generic `roleOf` attribute or custom `roleOfPerson`-like attributes to current roles like `nc:PersonType`, `nc:OrganizationType`, and the others.

This would let...

- most users fill person information directly into their role elements rather than having to use RoleOf elements
- make it easier for domain and IEPD developers to not get it wrong when building the schema
- still let messages use pointers from roles to roleOf elements whenever needed

**Current inline**

```xml
<j:CrashDriver>
  <nc:RoleOfPerson>
    <nc:PersonName>
      <nc:PersonFullName>John Doe</nc:PersonFullName>
    </nc:PersonName>
    <nc:PersonBirthDate>
      <nc:Date>1966-06-06</nc:Date>
    </nc:PersonBirthDate>
  </nc:RoleOfPerson>
  <j:CrashDriverViolationCode>A10</j:CrashDriverViolationCode>
  <j:CrashDrivingViolationCode>S16</j:CrashDrivingViolationCode>
</j:CrashDriver>
```

**Proposed inline**

```xml
<j:CrashDriver>
  <!-- No nc:RoleOfPerson element wrapping person content from Core -->
  <nc:PersonName>
    <nc:PersonFullName>John Doe</nc:PersonFullName>
  </nc:PersonName>
  <nc:PersonBirthDate>
    <nc:Date>1966-06-06</nc:Date>
  </nc:PersonBirthDate>
  <j:CrashDriverViolationCode>A10</j:CrashDriverViolationCode>
  <j:CrashDrivingViolationCode>S16</j:CrashDrivingViolationCode>
</j:CrashDriver>
```

**Current reference**

```xml
<j:CrashDriver>
  <nc:RoleOfPerson structures:ref="BRAVO" xsi:nil="true"/>
  <j:CrashDriverViolationCode>A10</j:CrashDriverViolationCode>
  <j:CrashDrivingViolationCode>S16</j:CrashDrivingViolationCode>
</j:CrashDriver>

<nc:Person structures:id="BRAVO">
  <nc:PersonName>
    <nc:PersonFullName>John Doe</nc:PersonFullName>
  </nc:PersonName>
  <nc:PersonBirthDate>
    <nc:Date>1966-06-06</nc:Date>
  </nc:PersonBirthDate>
</nc:Person>
```

**Proposed reference**

```xml
<j:CrashDriver nc:roleOfPerson="BRAVO">
  <!-- nc:RoleOfPerson element removed -->
  <j:CrashDriverViolationCode>A10</j:CrashDriverViolationCode>
  <j:CrashDrivingViolationCode>S16</j:CrashDrivingViolationCode>
</j:CrashDriver>

<nc:Person structures:id="BRAVO">
  <nc:PersonName>
    <nc:PersonFullName>John Doe</nc:PersonFullName>
  </nc:PersonName>
  <nc:PersonBirthDate>
    <nc:Date>1966-06-06</nc:Date>
  </nc:PersonBirthDate>
</nc:Person>
```

There are 94 uses of RoleOf elements currently in the draft 5.1 release.  Of these, 76 are single-representation roles (`j:StaffMemberType` contains `nc:RoleOfPerson`) and could be converted to extensions.

Role attributes would need to be added to the following types:

- nc:BinaryType
- nc:DocumentType
- nc:FacilityType
- nc:ItemType
- nc:PersonType
- nc:OrganizationType
- biom:BiometricType
- im:Alien
- it:PartyType
- mo:UnitType

Guidance for a domain or an IEPD that wants to use something from another namespace as a role that isn't already set up for that could be to create an augmentation and add the role attribute there.  For example, Justice uses biom:BiometricType as a role for evidence, but the Biometrics domain does not use the role.  Biometrics could choose to add it, or Justice could augment the role.

As now, the role attribute could point to any element of the type in which it is defined (e.g., `nc:Item`) or a specialization (e.g., `nc:Vehicle`).

```xml
<!-- Base type properties available through extension can be provided inline -->
<nc:Weapon>
  <nc:ItemDescriptionText>Older, dark gray truck</nc:ItemDescriptionText>
  <nc:WeaponUsageText>Knocked down a mailbox</nc:WeaponUsageText>
</nc:Weapon>

<!-- Specialized properties require using a reference (also true for the current approach) -->
<nc:Weapon nc:roleOfItem="v1">
  <nc:ItemDescriptionText>Older, dark gray truck</nc:ItemDescriptionText>
  <nc:WeaponUsageText>Knocked down a mailbox</nc:WeaponUsageText>
</nc:Weapon>

<nc:Vehicle structures:id="v1">
  <nc:ItemDescriptionText>Older, dark gray truck</nc:ItemDescriptionText>
  <j:VehicleAugmentation>
    <j:VehicleMakeCode>FORD</j:VehicleMakeCode>
    <j:VehicleModelCode>FORD-F100</j:VehicleModelCode>
  </j:VehicleAugmentation>
</nc:Vehicle>
```

Going back to representations and the victim example, we might change it so that a victim could have multiple representations, and each representation would be able to use the updated role syntax.

**Current inline**

```xml
<j:Victim>
  <nc:RoleOfPerson>
    <nc:PersonName>
      <nc:PersonFullName>John Doe</nc:PersonFullName>
    </nc:PersonName>
  </nc:RoleOfPerson>
  <j:VictimStatementText>I was ...</j:VictimStatementText>
</j:Victim>
```

**Proposed inline**

```xml
<j:Victim>
  <j:VictimPerson>
    <nc:PersonName>
      <nc:PersonFullName>John Doe</nc:PersonFullName>
    </nc:PersonName>
  </j:VictimPerson>
  <j:VictimStatementText>I was ...</j:VictimStatementText>
</j:Victim>
```

`j:VictimPerson` above would be substitutable for abstract element `j:VictimRepresentation`, as would `j:VictimOrganization` and `j:VictimItem`.

**Current reference**

```xml
<j:Victim>
  <nc:RoleOfPerson structures:ref="BRAVO" xsi:nil="true"/>
  <j:VictimStatementText>I was ...</j:VictimStatementText>
</j:Victim>

<nc:Person structure:id="BRAVO">
  <nc:PersonName>
    <nc:PersonFullName>John Doe</nc:PersonFullName>
  </nc:PersonName>
</nc:Person>
```

**Proposed reference**

```xml
<j:Victim>
  <j:VictimPerson nc:roleOfPerson="BRAVO" xsi:nil="true">
  <j:VictimStatementText>I was ...</j:VictimStatementText>
</j:Victim>

<nc:Person structure:id="BRAVO">
  <nc:PersonName>
    <nc:PersonFullName>John Doe</nc:PersonFullName>
  </nc:PersonName>
</nc:Person>
```

Of the 94 usages of role of elements mentioned above, 19 appear under types with multiple roles.  The following would either need to be converted to use the representation pattern, or in some cases, to extend `nc:EntityType` (`j:LesseeType`, `j:LessorType`, `j:LienHolderType`, `j:PawnBrokerType`).

- j:EvidenceType
  - nc:RoleOfItem
  - j:RoleOfBinary
  - j:RoleOfBiometric
- j:LesseeType
  - nc:RoleOfPerson
  - nc:RoleOfOrganization
- j:LessorType
  - nc:RoleOfPerson
  - nc:RoleOfOrganization
- j:LienHolderType
  - nc:RoleOfPerson
  - nc:RoleOfOrganization
- j:PawnBrokerType
  - nc:RoleOfPerson
  - nc:RoleOfOrganization
- j:SubjectType
  - nc:RoleOfPerson
  - nc:RoleOfOrganization
- j:VictimType
  - nc:RoleOfPerson
  - nc:RoleOfOrganization
  - nc:RoleOfItem
- mo:TargetType
  - nc:RoleOfPerson
  - mo:RoleOfFacility
  - mo:RoleOfUnit

Notes:

- Attribute `roleOf` might look better when used with representations like here; maybe `roleOfPerson` is a little clearer with the CrashDriver example above?
- Requires custom elements names (e.g., `VictimPerson`, `VictimOrganization`) instead of the reusable generic ones.

This reorganizes things so (1) representations are always done the same way and (2) role syntax is always available by default but only used when needed.  Any and all person extensions will have access to the roleOf attribute at any time, without requiring any special effort on the part of the schema developer.

Would then suggest going back and fixing the types like `nc:CountryType` and `nc:LanguageType`.

**Current**

- `nc:CountryType`, with a `nc:CountryRepresentation` element (text, name, and code substitutions)

**Proposed**

- `nc:CountryIdentifierType`, with a `nc:CountryIdentifierRepresentation` element (text, name and codes), or
- `nc:CountryType`, with a `nc:CountryIdentifierAbstract` element (text, name, and codes)

**Reference**

The following are the existing representation patterns we have:

- em:NotificationType
  - em:NotificationRepresentation
- mo:SettingDataType
  - mo:SettingDataRepresentation
- nc:CountryType
  - nc:CountryRepresentation
- nc:DateType
  - nc:DateRepresentation
- nc:EducationLevelType
  - nc:EducationLevelRepresentation
- nc:EducationQualificationType
  - nc:EducationQualificationRepresentation
- nc:EntityType
  - nc:EntityRepresentation
- nc:LanguageType
  - nc:LanguageRepresentation
- nc:StateType
  - nc:StateRepresentation
- nc:StreetDirectionalType
  - nc:StreetDirectionalRepresentation

**Comment by cdmgtri** [comment]
Migrated to niemopen/niem-naming-design-rules#6 and niemopen/niem-naming-design-rules#7
