### ISSUE TITLE
Update the `niem-xs` Namespace for Conformance/Consistency?

### ISSUE THREAD

**Issue by TomCarlson-NTAC** [NIEM/NIEM-NDR#116]
The NDR has exceptions for type names in the `niem-xs` namespace (e.g., `niem-xs:string` instead of `niem-xs:StringType`).  Get rid of the exception and make the names conformant?

Dr. Scott: But that implies it's something more complex.

**Comment by cdmgtri** [comment]
Migrated to niemopen/niem-naming-design-rules#15
