### ISSUE TITLE
Table 10-2: Representation terms - Rename as "Property representation terms"?

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-NDR#43]
[Table 10-2: Representation terms](https://rawgit.com/NIEM/NIEM-NDR/niem-ndr-4.0beta2/niem-ndr-4.0beta2.html#table_10-2)

The occasional references to this table and "component name" or just "name" seem a little fuzzy since this table is exclusively property representation terms.  

Second and third sentences of paragraph preceding Table 10-2:

> ...NIEM uses a standard set of representation terms in the representation portion of a NIEM-conformant component name. Table 10-2, Representation terms, below, lists the primary representation terms and a definition for the concept associated with the use of that term...

Also, it is mentioned close above at the beginning of Section [10.8.7. Representation terms](https://rawgit.com/NIEM/NIEM-NDR/niem-ndr-4.0beta2/niem-ndr-4.0beta2.html#section_10.8.7) that types have the representation term "Type", but "Type" does not show up in the table named "Representation terms".

**Comment by webb** [comment]
I think it's OK that representation terms have the little bit of fuzziness.

What would be a good definition for "Type" in the representation terms table?

**Comment by webb** [comment]
One factor here is that, although not required, the representation terms appear in many type names.

**Comment by webb** [comment]
I think we're OK where we are. Declining.

**Comment by webb** [comment]
Add an additional representation terms table for types.
