### ISSUE TITLE
Incorporate description of Linked Data into §5 and §12.2.2

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-NDR#58]
The NDR jumps to "linked data" without providing any description of what it is or why it's relevant or useful. Incorporate some description of Linked Data into §5 and §12.2.2. Doesn't need to be deep, but should be helpful.

**Comment by webb** [comment]
I'm reluctant to point to one of the top responses to the term "linked data" in google, just for informative purposes. Maybe some supporting text would help, if you'd like to suggest some.

**Comment by webb** [comment]
Original description:  Add a link to more information about Linked Data in Section 12.2.2 #58 

[12.2.2. Uniform resource identifiers in NIEM data](https://rawgit.com/NIEM/NIEM-NDR/niem-ndr-4.0beta2/niem-ndr-4.0beta2.html#section_12.2.2)

First paragraph, first sentence:

> NIEM supports the linked data methodology through the use of ...

Suggest adding a link to more information about Linked Data.  
Maybe [Linked Data](https://www.w3.org/standards/semanticweb/data)
