### ISSUE TITLE
Persistent rule IDs or mappings across NDR versions?

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-NDR#65]
Understand that rule numbers will change across NDR versions as rules are added or removed.  Is there an easy way to link the corresponding rules across different versions to make it easier to update documentation, tools, and/or training that reference the NDR?

For example, is there a way to link rules
- NDR 3.0, Rule 9-29 ("Complex content uses extension"), and
- NDR 4.0, Rule 9-30 ("Complex content uses extension")

Less trivial if the rule title changes across versions in addition to the rule number.

Saw the ndr-id-map.xml file, which may serve this purpose(?), although not all rules have values for descriptiveID.  Are these descriptiveIDs persistent?  Does this file exist for NDR 3.0?

**Comment by webb** [comment]
Users can map descriptiveIDs from the map file of one version of the specification to that of another. Values for  "descriptiveID" will be persistent unless the rule changes significantly.

**Comment by webb** [comment]
This is supported by the `ndr-id-map.xml` file in each NDR release.
