### ISSUE TITLE
new rule? Prefix rdf: must map to http://www.w3.org/1999/02/22-rdf-syntax-ns

### ISSUE THREAD

**Issue by iamdrscott** [NIEM/NIEM-NDR#77]
I am writing a NIEM XML to JSON translator. This causes me to think of all the horrible things that could appear in a conforming XML document.  For example,

`xmlns:rdf="http://my/trick/pony`

Handling that is a considerable PITA.  And I think it breaks the RDF mappings described in NDR [Section 5.6. Mapping of NIEM concepts to RDF concepts](https://reference.niem.gov/niem/specification/naming-and-design-rules/4.0/niem-ndr-4.0.html#section_5.6).  So how about we just forbid it?

We should probably also add RDF to [Section 2.3. Use of namespaces and namespace prefixes](https://reference.niem.gov/niem/specification/naming-and-design-rules/4.0/niem-ndr-4.0.html#section_2.3).  Right now the RDF mappings in section 5.6 just assume you know what `rdf:` means.

**Comment by webb** [comment]
Definitely an oversight. What if we were to add rdf to the list of namespaces in [§2.3. Use of namespaces and namespace prefixes](https://reference.niem.gov/niem/specification/naming-and-design-rules/4.0/niem-ndr-4.0.html#section_2.3)? That's how we handle all the other namespaces: we say "what we mean" without insisting on normative use of prefixes in user documents.

**Comment by iamdrscott** [comment]
I suppose I don't _really_ want to insist on this one normative prefix.  And if we're careful with the wording of NDR 5.6, we probably don't have to.

Perhaps we can meet in the middle with some NIEM conventions / best practice, probably in a different document. For example, the JSON-LD context we published for NIEM 4.0 or was it (4.1?) presumes you are using the conventional prefixes in your JSON, even though that's not mandatory. Life is better when all the namespace declarations appear on the document element. And so forth...

**Comment by webb** [comment]
The NDR v5 current draft defines what "rdf" and "rdfs" denote in section 5.6. Mapping of NIEM concepts to RDF concepts.
