### ISSUE TITLE
nc:AssociationType should extend structures:ObjectType instead of structures:AssociationType

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-NDR#78]
Issue submitted to https://github.com/NIEM/NIEM-Releases/issues/23: 

structures:ObjectType and structures:AssociationType are similar - except for name of AugmentationPoint

When nc:AssociationType is instantiated, it has two elements/properties with the same name:
nc:AssociationAugmentationPoint and structures:AssociationAugmentationPoint

When object types are used in other tools (e.g. Java) to implement the interface - the two properties with the same name are not allowed.

If nc:AssociationType was extending structures:ObjectType then nc:AssociationAugmentationPoint provides a place to augment nc:AssociationType, there would be no duplicate properties with the same name and structures:AssociationType could be deprecated.

**Comment by webb** [comment]
Developers are free to omit one of (structures:AssociationAugmentationPoint,nc:AssociationAugmentationPoint) from their subset, or to configure JAXB configuration to disambiguate the two properties. Revision of nc:AssociationType is out of the scope of the Naming and Design Rules. The current definition of nc:AssociationType is consistent with the NDR.
